// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user.proto

package lizsa.userservice.proto;

public final class User {
  private User() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GrpcUser_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GrpcUser_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nuser.proto\032\036google/protobuf/wrappers.p" +
      "roto\"$\n\010GrpcUser\022\n\n\002id\030\001 \001(\003\022\014\n\004name\030\002 \001" +
      "(\t2C\n\013UserService\0224\n\007getUser\022\034.google.pr" +
      "otobuf.StringValue\032\t.GrpcUser\"\000B\033\n\027lizsa" +
      ".userservice.protoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.WrappersProto.getDescriptor(),
        });
    internal_static_GrpcUser_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_GrpcUser_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GrpcUser_descriptor,
        new java.lang.String[] { "Id", "Name", });
    com.google.protobuf.WrappersProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
